### ISSUE TITLE
Please provide example files

### ISSUE THREAD

**Issue by novoid** [smaximov/org-doc#1]
Hi!

I stumbled on your tool via http://www.reddit.com/r/emacs/comments/4vr6t8/orgcommentary_generate_and_update_elisp_library/ 

It'd be great when you could add a fully working example to your repo. For someone who wants to get a short overview, your great but detailed information is overwhelming. Either as stand-alone files in an example folder or on the top of your README you should add a file that the user is creating and the derived file(s) your code is producing.

Thanks!

**Comment by smaximov** [comment]
Actually, this repository _is_ a fully working example. The "Commentary" section of `org-commentary.el` is generated using the content of `README.org` and the "Change Log" section uses the content of `CHANGELOG.org`. The generation command is hidden inside the "update-headers" target of `Makefile`.

But thanks for the suggestion, anyway. I will try to improve the docs to make the above mentioned fact clear to users. Additional examples won't harm, too.

**Comment by novoid** [comment]
As a tech-savvy guy, "the repos as an example" is really cool.

However, I did not get it.

Still, I do think that a minimal example could help to transport your idea.
